debug-mode: false

prefixes:
  default-prefix:
    prefix-string: ""
    color-code: "&7"
    placeholders-color: "&3"

chat-sounds:
  enabled: true
  sender-only: false
  sound: ui.button.click
  volume: 1.0
  pitch: 1.0

chat-item:
  enabled: true
  trigger-pattern: "[i]"

user-mention:
  enabled: true
  sound: entity.experience_orb.pickup
  volume: 1.0
  pitch: 1.0

permissions:
  global-permission: chatutilities.*
  chat-formats:
    colored: chatutilities.chat.colored # This allows players to write normal colors in chat.
    special: chatutilities.chat.special # This allows players to use special characters to edit the format of a chat message.
  chat-item:
    use: chatutilities.chat-item.use
  chat-utilities-command:
    main: chatutilities.command.main
    reload: chatutilities.command.reload